/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ANTONY
 */
public class Interfaz_1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz_1.class.getName());

    /**
     * Creates new form Interfaz_1
     */
    public Interfaz_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        JFileChooser file= new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado = file.showOpenDialog(this);
        
        if (resultado==JFileChooser.APPROVE_OPTION) {
            java.io.File archivo= file.getSelectedFile();
            
            if (archivo.getName().toLowerCase().endsWith(".txt")) {
                JOptionPane.showMessageDialog(this, "Archico TXT seleccionado"+ archivo.getAbsolutePath(), "Archivo Seleccionado", JOptionPane.INFORMATION_MESSAGE);
                
                try(BufferedReader reader=new BufferedReader(
                        new InputStreamReader(new FileInputStream(archivo),StandardCharsets.UTF_8))) 
                {
                 
                 StringBuilder secuenciaCompleta= new StringBuilder();
                 String line;
                 
                 //Leer todo el archivo y concatenar las lineas
                 while((line=reader.readLine())!=null){
                     secuenciaCompleta.append(line.trim());
                 }
                    //System.out.println(secuenciaCompleta);
                    
                 
                 //Procesar la secuencia completa
                 String secuenciaADN = secuenciaCompleta.toString();
                 StringBuilder triletesConComas = new StringBuilder();
                 
                    // Dividir en tripletes y agregar comas
                    for (int i = 0; i <= secuenciaADN.length() -3 ; i+=3) {
                        String triplete= secuenciaADN.substring(i,i+3);
                        triletesConComas.append(triplete);
                        
                        // Agregar coma si no es el último triplete
                        if (i < secuenciaADN.length() -3) {
                            triletesConComas.append("\n");
                        }
                        
                    }
                    System.out.println(triletesConComas);
                reader.close();
                 
                }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Error al leer el archivo"+e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

            }else{
                JOptionPane.showMessageDialog(this, "El archivo seleccionado no es un archivo .txt válido", "Error de Selección", JOptionPane.WARNING_MESSAGE);
            }
        }else if (resultado==JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(this, "Selección de archivo cancelada.", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
        }else if (resultado== JFileChooser.ERROR_OPTION) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al abrir el diálogo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_CargarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz_1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
